### PR TITLE
Update the discussion link in README.md?

### PR DESCRIPTION
**Pull request by foxcode64**
Don't know if you want to update the README.md file with the link to your Sononym discussion page rather than slice mate danoise.

### CODE REVIEW

**Comment by foxcode64** [comment]
Updated.

**Comment by bjorn-nesby** [comment]
Wow, I just discovered this pull request. Especially the autodetection of paths on linux is interesting, I was not entirely sure how to go about this. 

Seems the editor you're using insists on adding or removing whitespace/line-breaks btw. Just FYI, it does make things harder to read.

**Comment by foxcode64** [comment]
Ah, yes (I used an external editor), very sorry about that, I stripped the trailing whitespace on save, inadvertently complicating the diff.  Just lines 544-552 and 569-577 in App.lua that were added to.

As for the Linux detection I was just messing about with an idea of using 'find' (comes installed with most distros) to search the users home directory for the Sononym install path.  Probably isn't amazing amazing robust (hence why I haven't mentioned it), but it worked for me and it might give you an idea on how to go about it :)

**Comment by foxcode64** [comment]
The diff should look more like this -> https://github.com/4Tey/xrnx/commit/04353ee3621bb08c2cedf08cb2ab14df90ad4a51  My mistake danoise :blush:

Just one tiny quick side note: I don't know if you want to add the 'cFileMonitor.lua' file to your cLib repo? ->  https://github.com/renoise/cLib/tree/master/classes

**Pull request closed without merging**
